nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Models/Forums/ForumGroupListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Forums
{
    /// <summary>
    /// Represents a forum group list model
    /// </summary>
    public partial class ForumGroupListModel : BasePagedListModel<ForumGroupModel>
    {
    }
}

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Models/Forums/ForumGroupModel.cs
using System;
using Nop.Web.Framework.Mvc.ModelBinding;
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Forums
{
    /// <summary>
    /// Represents a forum group model
    /// </summary>
    public partial class ForumGroupModel : BaseNopEntityModel
    {
        #region Properties

        [NopResourceDisplayName("Admin.ContentManagement.Forums.ForumGroup.Fields.Name")]
        public string Name { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.Forums.ForumGroup.Fields.DisplayOrder")]
        public int DisplayOrder { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.Forums.ForumGroup.Fields.CreatedOn")]
        public DateTime CreatedOn { get; set; }

        #endregion
    }
}

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Models/Forums/ForumGroupSearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Forums
{
    /// <summary>
    /// Represents a forum group search model
    /// </summary>
    public partial class ForumGroupSearchModel : BaseSearchModel
    {
        #region Ctor

        public ForumGroupSearchModel()
        {
            ForumSearch = new ForumSearchModel();
        }

        #endregion

        #region Properties

        public ForumSearchModel ForumSearch { get; set; }

        #endregion
    }
}

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Models/Forums/ForumListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Forums
{
    /// <summary>
    /// Represents a forum list model
    /// </summary>
    public partial class ForumListModel : BasePagedListModel<ForumModel>
    {
    }
}

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Models/Forums/ForumModel.cs
using System;
using System.Collections.Generic;
using Nop.Web.Framework.Mvc.ModelBinding;
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Forums
{
    /// <summary>
    /// Represents a forum list model
    /// </summary>
    public partial class ForumModel : BaseNopEntityModel
    {
        #region Ctor

        public ForumModel()
        {
            ForumGroups = new List<ForumGroupModel>();
        }

        #endregion

        #region Properties

        [NopResourceDisplayName("Admin.ContentManagement.Forums.Forum.Fields.ForumGroupId")]
        public int ForumGroupId { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.Forums.Forum.Fields.Name")]
        public string Name { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.Forums.Forum.Fields.Description")]
        public string Description { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.Forums.Forum.Fields.DisplayOrder")]
        public int DisplayOrder { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.Forums.Forum.Fields.CreatedOn")]
        public DateTime CreatedOn { get; set; }

        public List<ForumGroupModel> ForumGroups { get; set; }

        #endregion
    }
}

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Models/Forums/ForumSearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Forums
{
    /// <summary>
    /// Represents a forum search model
    /// </summary>
    public partial class ForumSearchModel : BaseSearchModel
    {
        #region Properties

        public int ForumGroupId { get; set; }

        #endregion
    }
}

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Controllers/ForumController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain.Forums;
using Nop.Services.Forums;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Forums;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class ForumController : BaseAdminController
    {
        #region Fields

        private readonly IForumModelFactory _forumModelFactory;
        private readonly IForumService _forumService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;

        #endregion

        #region Ctor

        public ForumController(IForumModelFactory forumModelFactory,
            IForumService forumService,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService)
        {
            _forumModelFactory = forumModelFactory;
            _forumService = forumService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
        }

        #endregion

        #region Methods

        #region List

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageForums))
                return AccessDeniedView();

            //prepare model
            var model = _forumModelFactory.PrepareForumGroupSearchModel(new ForumGroupSearchModel());

            return View(model);
        }

        [HttpPost]
        public virtual IActionResult ForumGroupList(ForumGroupSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageForums))
                return AccessDeniedDataTablesJson();

            //prepare model
            var model = _forumModelFactory.PrepareForumGroupListModel(searchModel);

            return Json(model);
        }

        [HttpPost]
        public virtual IActionResult ForumList(ForumSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageForums))
                return AccessDeniedDataTablesJson();

            //try to get a forum group with the specified id
            var forumGroup = _forumService.GetForumGroupById(searchModel.ForumGroupId)
                ?? throw new ArgumentException("No forum group found with the specified id");

            //prepare model
            var model = _forumModelFactory.PrepareForumListModel(searchModel, forumGroup);

            return Json(model);
        }

        #endregion

        #region Create

        public virtual IActionResult CreateForumGroup()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageForums))
                return AccessDeniedView();

            //prepare model
            var model = _forumModelFactory.PrepareForumGroupModel(new ForumGroupModel(), null);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult CreateForumGroup(ForumGroupModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageForums))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var forumGroup = model.ToEntity<ForumGroup>();
                forumGroup.CreatedOnUtc = DateTime.UtcNow;
                forumGroup.UpdatedOnUtc = DateTime.UtcNow;
                _forumService.InsertForumGroup(forumGroup);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.ContentManagement.Forums.ForumGroup.Added"));

                return continueEditing ? RedirectToAction("EditForumGroup", new { forumGroup.Id }) : RedirectToAction("List");
            }

            //prepare model
            model = _forumModelFactory.PrepareForumGroupModel(model, null, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        public virtual IActionResult CreateForum()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageForums))
                return AccessDeniedView();

            //prepare model
            var model = _forumModelFactory.PrepareForumModel(new ForumModel(), null);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult CreateForum(ForumModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageForums))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var forum = model.ToEntity<Forum>();
                forum.CreatedOnUtc = DateTime.UtcNow;
                forum.UpdatedOnUtc = DateTime.UtcNow;
                _forumService.InsertForum(forum);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.ContentManagement.Forums.Forum.Added"));

                return continueEditing ? RedirectToAction("EditForum", new { forum.Id }) : RedirectToAction("List");
            }

            //prepare model
            model = _forumModelFactory.PrepareForumModel(model, null, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        #endregion

        #region Edit

        public virtual IActionResult EditForumGroup(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageForums))
                return AccessDeniedView();

            //try to get a forum group with the specified id
            var forumGroup = _forumService.GetForumGroupById(id);
            if (forumGroup == null)
                return RedirectToAction("List");

            //prepare model
            var model = _forumModelFactory.PrepareForumGroupModel(null, forumGroup);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult EditForumGroup(ForumGroupModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageForums))
                return AccessDeniedView();

            //try to get a forum group with the specified id
            var forumGroup = _forumService.GetForumGroupById(model.Id);
            if (forumGroup == null)
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                forumGroup = model.ToEntity(forumGroup);
                forumGroup.UpdatedOnUtc = DateTime.UtcNow;
                _forumService.UpdateForumGroup(forumGroup);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.ContentManagement.Forums.ForumGroup.Updated"));

                return continueEditing ? RedirectToAction("EditForumGroup", forumGroup.Id) : RedirectToAction("List");
            }

            //prepare model
            model = _forumModelFactory.PrepareForumGroupModel(model, forumGroup, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        public virtual IActionResult EditForum(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageForums))
                return AccessDeniedView();

            //try to get a forum with the specified id
            var forum = _forumService.GetForumById(id);
            if (forum == null)
                return RedirectToAction("List");

            //prepare model
            var model = _forumModelFactory.PrepareForumModel(null, forum);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult EditForum(ForumModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageForums))
                return AccessDeniedView();

            //try to get a forum with the specified id
            var forum = _forumService.GetForumById(model.Id);
            if (forum == null)
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                forum = model.ToEntity(forum);
                forum.UpdatedOnUtc = DateTime.UtcNow;
                _forumService.UpdateForum(forum);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.ContentManagement.Forums.Forum.Updated"));

                return continueEditing ? RedirectToAction("EditForum", forum.Id) : RedirectToAction("List");
            }

            //prepare model
            model = _forumModelFactory.PrepareForumModel(model, forum, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        #endregion

        #region Delete

        [HttpPost]
        public virtual IActionResult DeleteForumGroup(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageForums))
                return AccessDeniedView();

            //try to get a forum group with the specified id
            var forumGroup = _forumService.GetForumGroupById(id);

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Views/Forum/CreateForum.cshtml
@model ForumModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.ContentManagement.Forums.Forum.CreateForum").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Manage forums");
}

<form asp-controller="Forum" asp-action="CreateForum" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.ContentManagement.Forums.Forum.CreateForum") 
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.ContentManagement.Forums.Forum.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ForumDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateForum", Model)
</form>

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Views/Forum/CreateForumGroup.cshtml
@model ForumGroupModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.ContentManagement.Forums.ForumGroup.CreateForumGroup").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Manage forums");
}

<form asp-controller="Forum" asp-action="CreateForumGroup" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.ContentManagement.Forums.ForumGroup.CreateForumGroup")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.ContentManagement.Forums.ForumGroup.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ForumGroupDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateForumGroup", Model)
</form>

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Views/Forum/EditForum.cshtml
@model ForumModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.ContentManagement.Forums.Forum.EditForum").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Manage forums");
}

<form asp-controller="Forum" asp-action="EditForum" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.ContentManagement.Forums.Forum.EditForum") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.ContentManagement.Forums.Forum.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="forum-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ForumDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateForum", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="forum-delete" asp-action="DeleteForum"/>

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Views/Forum/EditForumGroup.cshtml
@model ForumGroupModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.ContentManagement.Forums.ForumGroup.EditForumGroup").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Manage forums");
}

<form asp-controller="Forum" asp-action="EditForumGroup" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.ContentManagement.Forums.ForumGroup.EditForumGroup") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.ContentManagement.Forums.ForumGroup.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="forumgroup-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ForumGroupDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateForumGroup", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="forumgroup-delete" asp-action="DeleteForumGroup"/>

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Views/Forum/List.cshtml
@model ForumGroupSearchModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.ContentManagement.Forums").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Manage forums");
}

<div class="content-header clearfix">
    <h1 class="pull-left">
        @T("Admin.ContentManagement.Forums")
    </h1>
    <div class="pull-right">
        <a asp-action="CreateForumGroup" class="btn btn-primary">@T("Admin.ContentManagement.Forums.ForumGroup.CreateForumGroup")</a>
        <a asp-action="CreateForum" class="btn btn-primary">@T("Admin.ContentManagement.Forums.Forum.CreateForum")</a>
        @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ForumListButtons })
    </div>
</div>

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-body">
                    @await Html.PartialAsync("Table", new DataTablesModel
                    {
                        Name = "forumgroup-grid",
                        UrlRead = new DataUrl("ForumGroupList", "Forum", null),
                        PrimaryKeyColumn = nameof(ForumGroupModel.Id),
                        Length = Model.PageSize,
                        LengthMenu = Model.AvailablePageSizes,
                        ColumnCollection = new List<ColumnProperty>
                        {
                            new ColumnProperty(null)
                            {
                                Render = new RenderChildCaret(),
                                Width = "5",
                                Searchable = false,
                                ClassName =  NopColumnClassDefaults.ChildControl
                            },
                            new ColumnProperty(nameof(ForumGroupModel.Name))
                            {
                                Title = T("Admin.ContentManagement.Forums.ForumGroup.Fields.Name").Text,
                                Width = "300"
                            },
                            new ColumnProperty(nameof(ForumGroupModel.DisplayOrder))
                            {
                                Title = T("Admin.ContentManagement.Forums.ForumGroup.Fields.DisplayOrder").Text,
                                Width = "100",
                                ClassName =  NopColumnClassDefaults.CenterAll
                            },
                            new ColumnProperty(nameof(ForumGroupModel.CreatedOn))
                            {
                                Title = T("Admin.ContentManagement.Forums.ForumGroup.Fields.CreatedOn").Text,
                                Width = "200",
                                Render = new RenderDate()
                            },
                            new ColumnProperty(nameof(ForumGroupModel.Id))
                            {
                                Title = T("Admin.Common.Edit").Text,
                                Width = "50",
                                ClassName = NopColumnClassDefaults.Button,
                                Render = new RenderButtonEdit(new DataUrl("EditForumGroup"))
                            }
                        },
                        ChildTable = new DataTablesModel
                        {
                            Name = "forumdetails-grid",
                            UrlRead = new DataUrl("ForumList", "Forum", null),
                            IsChildTable = true,
                            Length = Model.PageSize,
                            LengthMenu = Model.AvailablePageSizes,
                            Filters = new List<FilterParameter>
                            {
                                new FilterParameter(nameof(ForumModel.ForumGroupId), nameof(ForumGroupModel.Id), true)
                            },
                            ColumnCollection = new List<ColumnProperty>
                            {
                                new ColumnProperty(nameof(ForumModel.Name))
                                {
                                    Title = T("Admin.ContentManagement.Forums.Forum.Fields.Name").Text,
                                    Width = "300"
                                },
                                new ColumnProperty(nameof(ForumModel.DisplayOrder))
                                {
                                    Title = T("Admin.ContentManagement.Forums.Forum.Fields.DisplayOrder").Text,
                                    Width = "150",
                                    ClassName =  NopColumnClassDefaults.CenterAll
                                },
                                new ColumnProperty(nameof(ForumModel.CreatedOn))
                                {
                                    Title = T("Admin.ContentManagement.Forums.Forum.Fields.CreatedOn").Text,
                                    Width = "150",
                                    Render = new RenderDate()
                                },
                                new ColumnProperty(nameof(ForumModel.Id))
                                {
                                    Title = T("Admin.Common.Edit").Text,
                                    Width = "50",
                                    ClassName = NopColumnClassDefaults.Button,
                                    Render = new RenderButtonEdit(new DataUrl("EditForum"))
                                }
                            }
                        }
                    })
                </div>
            </div>
        </div>
    </div>
</div>

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Views/Forum/_CreateOrUpdateForum.cshtml
@model ForumModel

<div asp-validation-summary="ModelOnly"></div>
<input asp-for="Id" type="hidden" />

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ForumDetailsTop, additionalData = Model })
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="ForumGroupId"/>
                        </div>
                        <div class="col-md-9">
                            <nop-select asp-for="ForumGroupId" asp-items="@(new SelectList(Model.ForumGroups, "Id", "Name"))" asp-required="true" />
                            <span asp-validation-for="ForumGroupId"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="Name"/>
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="Name" asp-required="true"/>
                            <span asp-validation-for="Name"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="Description"/>
                        </div>
                        <div class="col-md-9">
                            <nop-textarea asp-for="Description"></nop-textarea>
                            <span asp-validation-for="Description"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="DisplayOrder"/>
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="DisplayOrder"/>
                            <span asp-validation-for="DisplayOrder"></span>
                        </div>
                    </div>
                </div>
            </div>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ForumDetailsBottom, additionalData = Model })
        </div>
    </div>
</div>

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Views/Forum/_CreateOrUpdateForumGroup.cshtml
@model ForumGroupModel

<div asp-validation-summary="ModelOnly"></div>
<input asp-for="Id" type="hidden" />

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ForumGroupDetailsTop, additionalData = Model })
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="Name"/>
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="Name" asp-required="true"/>
                            <span asp-validation-for="Name"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="DisplayOrder"/>
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="DisplayOrder"/>
                            <span asp-validation-for="DisplayOrder"></span>
                        </div>
                    </div>
                </div>
            </div>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ForumGroupDetailsBottom, additionalData = Model })
        </div>
    </div>
</div>