nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Controllers/ReviewTypeController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain.Catalog;
using Nop.Services.Catalog;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Models.Catalog;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// Represent a review type controller
    /// </summary>
    public partial class ReviewTypeController : BaseAdminController
    {
        #region Fields

        private readonly ICustomerActivityService _customerActivityService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly IReviewTypeModelFactory _reviewTypeModelFactory;
        private readonly IReviewTypeService _reviewTypeService;

        #endregion

        #region Ctor

        public ReviewTypeController(ICustomerActivityService customerActivityService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            INotificationService notificationService,
            IPermissionService permissionService,
            IReviewTypeModelFactory reviewTypeModelFactory,
            IReviewTypeService reviewTypeService)
        {
            _reviewTypeModelFactory = reviewTypeModelFactory;
            _reviewTypeService = reviewTypeService;
            _customerActivityService = customerActivityService;
            _localizedEntityService = localizedEntityService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
        }

        #endregion

        #region Utilities

        protected virtual void UpdateReviewTypeLocales(ReviewType reviewType, ReviewTypeModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(reviewType,
                    x => x.Name,                    
                    localized.Name,
                    localized.LanguageId);

                _localizedEntityService.SaveLocalizedValue(reviewType,
                   x => x.Description,
                   localized.Description,
                   localized.LanguageId);
            }
        }

        #endregion

        #region Review type

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //select an appropriate panel
            SaveSelectedPanelName("catalogsettings-review-types");

            //we just redirect a user to the catalog settings page
            return RedirectToAction("Catalog", "Setting");
        }

        [HttpPost]
        public virtual IActionResult List(ReviewTypeSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedDataTablesJson();

            //prepare model
            var model = _reviewTypeModelFactory.PrepareReviewTypeListModel(searchModel);

            return Json(model);
        }

        public virtual IActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //prepare model
            var model = _reviewTypeModelFactory.PrepareReviewTypeModel(new ReviewTypeModel(), null);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Create(ReviewTypeModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var reviewType = model.ToEntity<ReviewType>();
                _reviewTypeService.InsertReviewType(reviewType);                

                //activity log
                _customerActivityService.InsertActivity("AddNewReviewType",
                    string.Format(_localizationService.GetResource("ActivityLog.AddNewReviewType"), reviewType.Id), reviewType);

                //locales                
                UpdateReviewTypeLocales(reviewType, model);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Settings.ReviewType.Added"));

                return continueEditing ? RedirectToAction("Edit", new { id = reviewType.Id }) : RedirectToAction("List");                
            }

            //prepare model
            model = _reviewTypeModelFactory.PrepareReviewTypeModel(model, null, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        public virtual IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //try to get an product review type with the specified id
            var reviewType = _reviewTypeService.GetReviewTypeById(id);
            if (reviewType == null)
                return RedirectToAction("List");

            //prepare model
            var model = _reviewTypeModelFactory.PrepareReviewTypeModel(null, reviewType);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Edit(ReviewTypeModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //try to get an review type with the specified id
            var reviewType = _reviewTypeService.GetReviewTypeById(model.Id);
            if (reviewType == null)
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                reviewType = model.ToEntity(reviewType);
                _reviewTypeService.UpdateReviewType(reviewType);

                //activity log
                _customerActivityService.InsertActivity("EditReviewType",
                    string.Format(_localizationService.GetResource("ActivityLog.EditReviewType"), reviewType.Id),
                    reviewType);

                //locales
                UpdateReviewTypeLocales(reviewType, model);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Settings.ReviewType.Updated"));

                return continueEditing ? RedirectToAction("Edit", new { id = reviewType.Id }) : RedirectToAction("List");                
            }

            //prepare model
            model = _reviewTypeModelFactory.PrepareReviewTypeModel(model, reviewType, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost]
        public virtual IActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //try to get an review type with the specified id
            var reviewType = _reviewTypeService.GetReviewTypeById(id);
            if (reviewType == null)
                return RedirectToAction("List");

            try
            {
                _reviewTypeService.DeleteReiewType(reviewType);

                //activity log
                _customerActivityService.InsertActivity("DeleteReviewType",
                    string.Format(_localizationService.GetResource("ActivityLog.DeleteReviewType"), reviewType),
                    reviewType);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Settings.ReviewType.Deleted"));

                return RedirectToAction("List");
            }
            catch (Exception exc)
            {
                _notificationService.ErrorNotification(exc);
                return RedirectToAction("Edit", new { id = reviewType.Id });
            }            
        }

        #endregion
    }
}

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Views/ReviewType/Create.cshtml
@model ReviewTypeModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Settings.ReviewType.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Catalog settings");
}

<form asp-controller="ReviewType" asp-action="Create" method="post" id="reviewtype-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Settings.ReviewType.AddNew")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Settings.ReviewType.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductReviewTypeButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Views/ReviewType/Edit.cshtml
@model ReviewTypeModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Settings.ReviewType.EditDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Catalog settings");
}

<form asp-controller="ReviewType" asp-action="Edit" method="post" id="reviewtype-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Settings.ReviewType.EditDetails") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Settings.ReviewType.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="reviewtype-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductReviewTypeButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="reviewtype-delete" />

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Views/ReviewType/List.cshtml
@model ReviewTypeSearchModel

<div class="panel-body">
    <p>
        <em>@T("Admin.Settings.ReviewType.Description")</em>
    </p>
    @await Html.PartialAsync("Table", new DataTablesModel
    {
        Name = "reviewtypes-grid",
        UrlRead = new DataUrl("List", "ReviewType", null),
        Length = Model.PageSize,
        LengthMenu = Model.AvailablePageSizes,
        ColumnCollection = new List<ColumnProperty>
        {
            new ColumnProperty(nameof(ReviewTypeModel.Name))
            {
                Title = T("Admin.Settings.ReviewType.Fields.Name").Text,
                Width = "300"
            },
            new ColumnProperty(nameof(ReviewTypeModel.IsRequired))
            {
                Title = T("Admin.Settings.ReviewType.Fields.IsRequired").Text,
                Width = "100",
                ClassName = NopColumnClassDefaults.CenterAll,
                Render = new RenderBoolean()
            },
            new ColumnProperty(nameof(ReviewTypeModel.VisibleToAllCustomers))
            {
                Title = T("Admin.Settings.ReviewType.Fields.VisibleToAllCustomers").Text,
                Width = "100",
                ClassName = NopColumnClassDefaults.CenterAll,
                Render = new RenderBoolean()
            },
            new ColumnProperty(nameof(ReviewTypeModel.DisplayOrder))
            {
                Title = T("Admin.Settings.ReviewType.Fields.DisplayOrder").Text,
                Width = "100",
                ClassName = NopColumnClassDefaults.CenterAll
            },
            new ColumnProperty(nameof(ReviewTypeModel.Id))
            {
                Title = T("Admin.Common.Edit").Text,
                Width = "100",
                ClassName =  NopColumnClassDefaults.Button,
                Render = new RenderButtonEdit(new DataUrl("~/Admin/ReviewType/Edit/"))
            }
        }
    })
</div>    
<div class="panel-footer">
    <a class="btn btn-primary" href="@Url.Action("Create", "ReviewType")">
        <i class="fa fa-plus-square"></i>
        @T("Admin.Common.AddNew")
    </a>
</div>

nopCommerce-release-4.30/src/Presentation/Nop.Web/Areas/Admin/Views/ReviewType/_CreateOrUpdate.cshtml
@model ReviewTypeModel

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductReviewTypeTop, additionalData = Model })
            <div class="panel panel-default">
                <div class="panel-body">
                    @(Html.LocalizedEditor<ReviewTypeModel, ReviewTypeLocalizedModel>("review-type-localized",
                    @<div>
                        <div class="form-group">
                            <div class="col-md-3">
                                <nop-label asp-for="@Model.Locales[item].Name" />
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="@Model.Locales[item].Name" />
                                <span asp-validation-for="@Model.Locales[item].Name"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3">
                                <nop-label asp-for="@Model.Locales[item].Description" />
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="@Model.Locales[item].Description" asp-template="RichEditor" />
                                <span asp-validation-for="@Model.Locales[item].Description"></span>
                            </div>
                        </div>
                        <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
                    </div>
                    ,
                    @<div>
                        <div class="form-group">
                            <div class="col-md-3">
                                <nop-label asp-for="Name" />
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="Name" asp-required="true" />
                                <span asp-validation-for="Name"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3">
                                <nop-label asp-for="Description" />
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="Description" asp-required="true" asp-template="RichEditor" />
                                <span asp-validation-for="Description"></span>
                            </div>
                        </div>
                    </div>
                    ))
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="DisplayOrder" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="DisplayOrder" />
                            <span asp-validation-for="DisplayOrder"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="IsRequired" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="IsRequired" />
                            <span asp-validation-for="IsRequired"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="VisibleToAllCustomers" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="VisibleToAllCustomers" />
                            <span asp-validation-for="VisibleToAllCustomers"></span>
                        </div>
                    </div>
                </div>
            </div>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductReviewTypeBottom, additionalData = Model })
        </div>
    </div>
</div>